# name: Build Spring Boot Project

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

# jobs:
#   build:
#     name: Build with Maven
#     runs-on: ubuntu-latest

#     steps:
#       #  Step 1: Checkout the code
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       #  Step 2: Set up JDK 17 (Temurin)
#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '17'
#           cache: 'maven'

#       #  Step 3: Build the project
#       - name: Build with Maven
#         run: mvn clean install -DskipTests

#       # Step 4: Upload to artifactory
#       - name: Upload JAR artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: springboot-build
#           path: target/*.jar


name: Multi-Job Spring Boot Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # allows manual run

jobs:
  # Job: Code Checkout and Compile
  compile:
    name: Compile Source Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile code
        run: mvn clean compile

  # Job: Run Tests (depends on compile)
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test

  # Job: Build Package (depends on test)
  package:
    name: Build JAR Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Package JAR
        run: mvn package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar
          retention-days: 5
